# Generated by Django 3.1.6 on 2021-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_workerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
