# Generated by Django 3.1.7 on 2021-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='81234567890', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
