# Generated by Django 3.1.7 on 2022-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210405_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Extra informations'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
