# Generated by Django 3.1.6 on 2021-02-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fullname', models.CharField(max_length=100)),
                ('recipient_fullname', models.CharField(max_length=100)),
                ('direct_take', models.BooleanField()),
                ('direct_take_address', models.CharField(blank=True, max_length=250)),
                ('direct_deliver', models.BooleanField()),
                ('direct_deliver_address', models.CharField(blank=True, max_length=250)),
                ('departure_date', models.DateField()),
                ('cargo_type', models.CharField(choices=[('PACK', 'Упаковка'), ('BARE', 'Без упаковки')], max_length=4)),
                ('cargo_len', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('additional_info', models.TextField(blank=True, max_length=5000)),
                ('arrival_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_warehouse', to='main.warehouse')),
                ('departure_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_warehouse', to='main.warehouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
