# Generated by Django 3.1.6 on 2021-02-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_arrival_warehouse', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_departure_warehouse', to='main.warehouse'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('CAR', 'Грузовик'), ('TRAIN', 'Поезд'), ('PLANE', 'Самолёт')], max_length=5)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupied_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_arrival_warehouse', to='main.warehouse')),
                ('departure_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_departure_warehouse', to='main.warehouse')),
                ('orders', models.ManyToManyField(to='main.Order')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending')),
            ],
        ),
    ]
