# Generated by Django 3.1.6 on 2021-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_warehouse_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_depth',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_len',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_width',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
