# Generated by Django 3.1.6 on 2021-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210301_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Грузовик'), ('CONF', 'Поезд')], default='WAIT', max_length=4),
        ),
    ]
