# Generated by Django 3.1.6 on 2021-03-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_info'),
        ('main', '0005_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
