# Generated by Django 3.1.6 on 2021-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210304_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Ожидается подтверждение'), ('CONF', 'Подтверждено')], default='WAIT', max_length=4),
        ),
        migrations.AlterField(
            model_name='sending',
            name='orders',
            field=models.ManyToManyField(blank=True, to='main.Order'),
        ),
    ]
