# Generated by Django 3.1.6 on 2021-03-08 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210308_1638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210305_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='Отправление'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Ожидается подтверждение'), ('CONF', 'Подтверждено')], default='WAIT', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrival_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_arrival_warehouse', to='main.warehouse', verbose_name='Склад получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_depth',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Глубина груза (см)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_len',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Длина груза (см)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.CharField(choices=[('PACK', 'Упаковка'), ('BARE', 'Без упаковки')], max_length=4, verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес груза (кг)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_width',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Ширина груза (см)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_departure_warehouse', to='main.warehouse', verbose_name='Склад отправления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direct_deliver',
            field=models.BooleanField(verbose_name='Нужно ли доставить получателю?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direct_deliver_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direct_take',
            field=models.BooleanField(verbose_name='Нужно ли забрать от отправителя?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direct_take_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='insurance_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость страховки (руб)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_fullname',
            field=models.CharField(max_length=100, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_fullname',
            field=models.CharField(max_length=100, verbose_name='ФИО отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='arrival_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_arrival_warehouse', to='main.warehouse', verbose_name='Склад получения'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='departure_date',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='departure_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_departure_warehouse', to='main.warehouse', verbose_name='Склад отправления'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='occupied_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Занятый объём в м^3'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='orders',
            field=models.ManyToManyField(blank=True, to='main.Order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общий объём в м^3'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер транспорта'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('CAR', 'Грузовик'), ('TRAIN', 'Поезд'), ('PLANE', 'Самолёт')], max_length=5, verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
    ]
