# Generated by Django 3.1.6 on 2021-03-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210308_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Ожидается подтверждение'), ('CONF', 'Подтверждено'), ('DECL', 'Отклонено')], default='WAIT', max_length=4, verbose_name='Статус'),
        ),
    ]
