# Generated by Django 3.1.6 on 2021-03-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210309_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Информация по заявке'),
        ),
    ]
