# Generated by Django 3.1.6 on 2021-03-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_sending_occupied_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrival_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departure_warehouse',
        ),
        migrations.AddField(
            model_name='order',
            name='arrival_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_arrival_city', to='main.city', verbose_name='Город получения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='departure_city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_departure_city', to='main.city', verbose_name='Город отправления'),
            preserve_default=False,
        ),
    ]
