# Generated by Django 3.1.7 on 2021-05-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210321_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('CAR', 'Грузовик'), ('TRAIN', 'Поезд'), ('PLANE', 'Самолёт'), ('SHIP', 'Корабль')], max_length=5, verbose_name='Тип транспорта'),
        ),
        migrations.CreateModel(
            name='TransitPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия (в данный пункт)')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город прибытия')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='Отправление')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport', verbose_name='Транспорт (до следующего пункта маршрута)')),
            ],
        ),
    ]
