# Generated by Django 3.1.7 on 2021-05-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210509_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitpoint',
            name='arrival_city',
        ),
        migrations.AddField(
            model_name='transitpoint',
            name='arrival_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse', verbose_name='Транзитный склад'),
            preserve_default=False,
        ),
    ]
