# Generated by Django 3.1.7 on 2022-07-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220719_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='arrival_city'),
        ),
    ]
