# Generated by Django 3.1.6 on 2021-02-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_workerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
